version: '2.1'
services:

  localstack:
    container_name: localstack
    image: localstack/localstack-full:0.12.14
    ports:
      - "4572:4572"
      - "4566:4566"

    environment:
      - SERVICES=s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
