service: tooling-s3-sqs

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline
  - serverless-mocha-plugin

functions:
  hello:
    handler: handler.hello
    events:
      - http: 
          method: get
          path: hello
